### ISSUE TITLE
fix: condo build fails when "building" a bunch of flat files

### ISSUE THREAD

**Issue by bsambrone** [automotiveMastermind/condo#131] opened 2017-10-30 23:36 UTC
When building a repository that contains no code (only yaml and jinja files), docker will fail when trying to build. It looks like some bools are missing? 

This behavior exists in both a hosted VSTS linux agent as well as running locally from a powershell session.

1>/root/.am/condo/cli/Targets/Compile/Dotnet.targets(15,34): error MSB4113: Specified condition " $(DotNetBuild) " evaluates to "" instead of a boolean. [/opt/vsts/work/1/s/condo.build]
1>Done Building Project "/opt/vsts/work/1/s/condo.build" (Publish target(s)) -- FAILED.

Current workaround is to add the following environment variables:
DotNetBuild = false
DotNetPublish = false
PolymerBuild = false
DockerBuild = false
DockerPush = false

**Comment by dmccaffery** [comment] 2017-10-31 01:46
Upon review, this was caused by manipulating the lifecycle of condo in such a way that dotnet-related targets were skipped while the publish target was still executed. Closing.

**Closed as completed by dmccaffery** 2017-10-31 01:46 UTC
Labels: bug
