### ISSUE TITLE
Publish target error during CI build

### ISSUE THREAD

**Issue by bsambrone** [automotiveMastermind/condo#144] opened 2017-11-10 21:49 UTC
When using condo to build a .sqlproj file locally, it works fine using the build file listed at the bottom. When ran on a hosted VSTS agent, I am greeted with:
       `"D:\a\1\s\condo.build" (Publish target) (1) ->
         D:\a\1\s\condo.build : error MSB4057: The target "Publish" does not exist in the project.`

Next I tried add env vars that I listed in issue [131](https://github.com/automotiveMastermind/condo/issues/131) and had the same result.

I have also tried using the condo.build file in it's vanilla format (while retaining the SetDacVersion stuff), and I get:
       `C:\Users\bsambrone\Source\Repos\am.database.ammdb\src\am.database.ammdb\am.database.ammdb.sqlproj(60,3): error MSB4019: The imported project "C:\Users\bsambrone\AppData\Local\Microso
\dotnet\sdk\2.0.3-servicing-007053\Microsoft\VisualStudio\v11.0\SSDT\Microsoft.Data.Tools.Schema.SqlTasks.targets" was not found. Confirm that the path in the <Import> declaration is correc
 and that the file exists on disk.`

Not trying to actually build with Condo, just get the semver benefit and write it out to a file so I can use it with good 'ol legacy msbuild.

\<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003"
         InitialTargets="Version" DefaultTargets="Version"\>
\<Target Name="SetDacVersion"\>
 \<SaveFile RepositoryRoot="$(RepositoryRoot)" FilePath="version.txt" Content="$(RecommendedRelease)" /\>
\</Target\>

\<PropertyGroup\>
 \<AfterPublish\>
    $(AfterPublish);
    SetDacVersion;
 \</AfterPublish\>
\</PropertyGroup\>

\<Target Name="Initialize" /\>

\<Target Name="Version" DependsOnTargets="Initialize" /\>
  
\<Import Project="$(CondoTargetsPath)\Goals.targets" /\>
\</Project\>

**Comment by dmccaffery** [comment] 2017-11-10 23:46
This is by design:

If you skip the import of the lifecycle, then the "Publish" target is not imported. The CI task group we use in VSTS at aM specifically calls the Publish target by default. Since its missing, it can't be called and results in the error you are seeing.

The easy solution for this at the moment is to add the following properties to your ```PropertyGroup``` in the condo.build file to stop condo from attempting to build the csproj files that are not using MSBuild 15.0:

```xml
<PropertyGroup>
  <DotNetRestore>false</DotNetRestore>
  <DotNetBuild>false</DotNetBuild>
  <DotNetPack>false</DotNetPack>
  <DotNetTest>false</DotNetTest>
  <DotNetPublish>false</DotNetPublish>
</PropertyGroup>

<Target Name="SetDacVersion">
  <SaveFile RepositoryRoot="$(RepositoryRoot)" FilePath="version.txt" Content="$(RecommendedRelease)" />
</Target>

<Import Project="$(CondoTargetsPath)Lifecycle.targets" />
<Import Project="$(CondoTargetsPath)Goals.targets" />

<AfterPublish>
  $(AfterPublish);
  SetDacVersion;
</AfterPublish>
```

Condo was skipping projects that weren't MSBuild 15.0 projects for all targets, but a race condition in the restore process of .csproj files was causing us some issues; so we reverted to doing the restore on the solution file -- this is what is causing the error importing the dacpac projects.

**Comment by dmccaffery** [comment] 2017-11-10 23:47
I will keep this open until you confirm this solution -- I'l also look into resolving the race condition on the csproj files through a different mechanism.

**Comment by dmccaffery** [comment] 2018-01-27 20:49
@bsambrone: closing. This should no longer be an issue. DotNet can be skipped entirely by setting the SKIP_DOTNET environment variable or setting <DotNetEnabled>false</DotNetEnabled> in the build file.

**Closed as completed by dmccaffery** 2018-01-27 20:49 UTC
Labels: question
